/**
 * schulNetz Rest API
 * schulNetz REST JSON API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@centerboard.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CourseOffer {
    offerId: string;

    titleShort: string;

    name?: string;

    publicationStart?: Date;

    publicationEnd?: Date;

    registrationDeadline?: Date;

    place?: string;

    mapLocation?: string;

    maxRegistrations?: number;

    canExceedMaxRegistrations?: boolean;

    currentRegistrationNumber?: number;

    courseStart?: Date;

    courseEnd?: Date;

    courseDays?: string;

    courseTimes?: string;

    courseRoom?: string;

    courseProfessor?: string;

    totalLessons?: number;

    costTotal?: string;

}
