/**
 * schulNetz Rest API
 * schulNetz REST JSON API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@centerboard.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ESchoolCourse {
    menu: string;

    title?: string;

    offerNumber?: number;

    type?: string;

    abstract?: string;

    content?: string;

    scope?: string;

    requirements?: string;

    certificate?: string;

    informationEvent?: string;

    additionalInformation?: string;

    links?: string;

    costDetails?: string;

    contactName?: string;

    contactPhone?: string;

    contactMail?: string;

    courseExecutions?: Array<models.CourseOffer>;

    infoEvents?: Array<models.CourseOffer>;

}
