/**
 * schulNetz Rest API
 * schulNetz REST JSON API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@centerboard.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface OfferType {
    id: string;

    title: string;

    titleShort?: string;

    infoText?: number;

    overviewFields?: Array<string>;

    detailFields?: Array<string>;

    tags?: Array<string>;

}
