/**
 * schulNetz Rest API
 * schulNetz REST JSON API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@centerboard.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Offer {
    id: string;

    title: string;

    titleShort?: string;

    offerNumber?: number;

    name?: string;

    abstract?: string;

    type?: string;

    menu?: string;

    content?: string;

    publicationStart?: Date;

    publicationEnd?: Date;

    registrationDeadline?: Date;

    scope?: string;

    place?: string;

    mapLocation?: string;

    requirements?: string;

    certificate?: string;

    informationEvent?: string;

    additionalInformation?: string;

    links?: string;

    maxRegistrations?: number;

    canExceedMaxRegistrations?: boolean;

    currentRegistrationNumber?: number;

    courseStart?: Date;

    courseEnd?: Date;

    courseDays?: string;

    courseTimes?: string;

    courseRoom?: string;

    courseProfessor?: string;

    totalLessons?: number;

    costTotal?: string;

    costDetails?: string;

    contactName?: string;

    contactPhone?: string;

    contactMail?: string;

}
