/**
 * schulNetz Rest API
 * schulNetz REST JSON API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@centerboard.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Registration {
    lastName: string;

    firstName: string;

    /**
     * Full First Name (eg Anna Lena)
     */
    fullFirstName?: string;

    gender?: Registration.GenderEnum;

    birthday?: Date;

    salutation?: string;

    addressLine1?: string;

    addressLine2?: string;

    postOfficeBox?: string;

    zip?: string;

    city?: string;

    canton?: string;

    country?: string;

    phone?: string;

    phoneOffice?: string;

    mobile?: string;

    telefax?: string;

    email?: string;

    emailPrivate?: string;

    /**
     * Alpha-2 code ISO-3166
     */
    nationality?: string;

    /**
     * Alpha-2 code ISO-3166
     */
    nationality2?: string;

    hometown?: string;

    hometown2?: string;

    dateEntry?: Date;

    dateExit?: Date;

    /**
     * Matrikel-Nr.
     */
    registerNr?: string;

    idNr?: string;

    externalKey?: string;

    /**
     * Swiss Social Security Number without separation points
     */
    socialSecurityNumber?: string;

    invoiceLastName?: string;

    invoiceFirstName?: string;

    invoiceCompany?: string;

    invoiceSalutation?: string;

    invoiceAddressLine1?: string;

    invoiceAddressLine2?: string;

    invoicePostOfficeBox?: string;

    invoiceZip?: string;

    invoiceCity?: string;

    invoiceCanton?: string;

    invoiceCountry?: string;

    invoicePhone?: string;

    invoicePhoneOffice?: string;

    invoiceTelefax?: string;

    comment?: string;

    offerIds: Array<string>;

}
export namespace Registration {
    export enum GenderEnum {
        Male = <any> 'male',
        Female = <any> 'female'
    }
}
